version: '3.1'
services:
  node:
    image: node:latest
    container_name: nodejs_app
    restart: always
    volumes: 
      - ./api:/app
    working_dir: 
      /app
    command: bash -c "npm install && npm run start:dev"
    ports: 
      - 3000:3000
    networks: 
      - backend
      - elastic

  mysql:
    image: mysql:latest
    container_name: db_app
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - ./volumes/db/:/var/lib/mysql
    ports: 
      - 3306:3306
    environment:
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: 'usuarios'
    networks: 
      - backend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./volumes/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.1
    container_name: kibana
    environment:
      SERVER_NAME: elasticsearch
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on: 
      - elasticsearch
    networks: 
      - elastic

networks:
  backend:
    driver: bridge
  elastic:
    driver: bridge